### ISSUE TITLE
Empty page when clicking "Create new workflow"

### ISSUE THREAD

**Issue by CennoxX** [magnusmanske/toolflow_rs#1]
I am logged in, click on "Create new workflow" and come to an empty page. In the console I see `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` and the network request to https://toolflow.toolforge.org/api.php?action=create_new_workflow has the following answer:

<pre>string(141) "INSERT INTO `workflow` (`name`,`json`,`state`,`user_id`,`ts_created`) VALUES ('Unnamed workflow','{"nodes":[],"edges":[]}','DRAFT',641,NOW())" string(123) "#0 /data/project/toolflow/public_html/api.php(225): ToolforgeCommon->getSQL(Object(mysqli), 'INSERT INTO `wo...') #1 {main}"
Fatal error: Uncaught Exception: ToolforgeCommon::getSQL: Field 'description' doesn't have a default value/1364 : INSERT INTO `workflow` (`name`,`json`,`state`,`user_id`,`ts_created`) VALUES ('Unnamed workflow','{"nodes":[],"edges":[]}','DRAFT',641,NOW()) in /data/project/magnustools/public_html/php/ToolforgeCommon.php:248 Stack trace: #0 /data/project/toolflow/public_html/api.php(225): ToolforgeCommon->getSQL(Object(mysqli), 'INSERT INTO `wo...') #1 {main} thrown in /data/project/magnustools/public_html/php/ToolforgeCommon.php on line 248</pre>

I get the same errors if I want to fork an existing workflow.

**Comment by magnusmanske** [comment]
Fixed now (in the UI repo: https://github.com/magnusmanske/toolflow/commit/28c14ec65d43f1ce85ceb9d4cbbdb0031ccdcaf9 )

**Comment by CennoxX** [comment]
Wow that was fast, thanks. It works now.
